.ALIASES
X_U1A           U1A(CLRbar=VCC D=N14639 CLK=CLK PREbar=VCC Q=T_FF Qbar=N14639 VCC=$G_DPWR GND=$G_DGND ) CN
+@D_FLIP_FLOP.SCHEMATIC1(sch_1):INS14311@7400.7474.Normal(chips)
U_DSTM2          DSTM2(VCC=$G_DPWR GND=$G_DGND 1=CLK ) CN @D_FLIP_FLOP.SCHEMATIC1(sch_1):INS14430@SOURCE.DigClock.Normal(chips)
V_V1            V1(+=VCC -=0 ) CN @D_FLIP_FLOP.SCHEMATIC1(sch_1):INS14955@SOURCE.VDC.Normal(chips)
_    _(Clk=CLK)
_    _(T_FF=T_FF)
_    _(VCC=VCC)
.ENDALIASES
